### PR TITLE
Improved import

### LINKED ISSUE #1: Words with multiple Strong's references not parsing to JSON
Example: εἰμί

### PR DESCRIPTION
**Pull request by jcuenod**
Better handles the syntax of dictionary.txt - strongs numbers are now an array in the json (even if there's only one) but fixes #1 & #3

### CODE REVIEW

**Comment by aaronshaf** [comment]
@jcuenod Dude, thank you for your work on this!

**Comment by jcuenod** [comment]
No problem - could you confirm that you're happy with the output it's producing?

**Comment by aaronshaf** [comment]
We need some rspec tests

**Comment by jcuenod** [comment]
I've got to admit, I'm pretty clueless when it comes to testing. I agree though in principle - all I did was run jsonlint on the output and from use can say that it seems to be working fine (I'm only using the definitions though).

**Comment by aaronshaf** [comment]
No problem. I'll try to add some tests at some point.

Thanks again for the contribution... super encouraging.

**Comment by jcuenod** [comment]
I'm using the data! https://github.com/jcuenod/theMarker (try highlighting future indicatives or passive forms of ἐγείρω in Matthew - the point is the ease with which it can be done but the dictionary is an awesome (and necessary) addition).

**Pull request merged**
